version: '3.3'

services:
  db:
    image: postgres:15.2
    restart: on-failure
    environment:
      - POSTGRES_USER=base_fastapi_project
      - POSTGRES_PASSWORD=base_fastapi_project
      - POSTGRES_DB=base_fastapi_project
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U base_fastapi_project -d base_fastapi_project
      interval: 30s
      timeout: 3s
      retries: 3

  redis:
    image: redis/redis-stack:7.2.0-RC1
    restart: on-failure
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
