version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    restart: on-failure
    depends_on:
      - db
      - redis
      - minio
    environment:
      REDIS_DSN: redis://redis:6379/
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: data_aggregator
      POSTGRES_PASSWORD: data_aggregator
      POSTGRES_DB: data_aggregator
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:15.2
    restart: on-failure
    environment:
      - POSTGRES_USER=data_aggregator
      - POSTGRES_PASSWORD=data_aggregator
      - POSTGRES_DB=data_aggregator

  redis:
    image: redis/redis-stack:7.2.0-RC1
    restart: on-failure
